spec_trans(root,'$initialise_machine',0).
spec_trans(0,'reserve(CUSTOMER1,1)',1).
spec_trans(0,'reserve(CUSTOMER2,1)',2).
spec_trans(0,'reserve(CUSTOMER1,2)',3).
spec_trans(0,'reserve(CUSTOMER2,2)',4).
spec_trans(0,'reserve(CUSTOMER1,3)',5).
spec_trans(0,'reserve(CUSTOMER2,3)',6).
spec_trans(1,'reserve(CUSTOMER1,1)',3).
spec_trans(1,'reserve(CUSTOMER2,1)',7).
spec_trans(1,'reserve(CUSTOMER1,2)',5).
spec_trans(1,'reserve(CUSTOMER2,2)',8).
spec_trans(1,'reserve(CUSTOMER1,3)',9).
spec_trans(1,'reserve(CUSTOMER2,3)',10).
spec_trans(1,'collect(CUSTOMER1)',12).
spec_trans(1,'collect(CUSTOMER1)',14).
spec_trans(6,'reserve(CUSTOMER1,1)',10).
spec_trans(6,'reserve(CUSTOMER2,1)',15).
spec_trans(6,'reserve(CUSTOMER1,2)',16).
spec_trans(6,'reserve(CUSTOMER2,2)',17).
spec_trans(6,'reserve(CUSTOMER1,3)',18).
spec_trans(6,'reserve(CUSTOMER2,3)',19).
spec_trans(2,'reserve(CUSTOMER1,1)',7).
spec_trans(2,'reserve(CUSTOMER2,1)',4).
spec_trans(2,'reserve(CUSTOMER1,2)',20).
spec_trans(2,'reserve(CUSTOMER2,2)',6).
spec_trans(2,'reserve(CUSTOMER1,3)',21).
spec_trans(2,'reserve(CUSTOMER2,3)',15).
spec_trans(2,'collect(CUSTOMER2)',23).
spec_trans(2,'collect(CUSTOMER2)',25).
spec_trans(19,'reserve(CUSTOMER1,1)',26).
spec_trans(19,'reserve(CUSTOMER2,1)',27).
spec_trans(19,'reserve(CUSTOMER1,2)',28).
spec_trans(19,'reserve(CUSTOMER2,2)',29).
spec_trans(19,'reserve(CUSTOMER1,3)',30).
spec_trans(19,'reserve(CUSTOMER2,3)',31).
spec_not_all_transitions_added(31).
spec_not_all_transitions_added(30).
spec_not_all_transitions_added(29).
spec_not_all_transitions_added(28).
spec_not_all_transitions_added(27).
spec_not_all_transitions_added(26).
spec_not_all_transitions_added(18).
spec_not_all_transitions_added(17).
spec_not_all_transitions_added(16).
spec_not_all_transitions_added(15).
spec_not_all_transitions_added(5).
spec_not_all_transitions_added(4).
spec_not_all_transitions_added(3).
spec_not_all_transitions_added(7).
spec_not_all_transitions_added(8).
spec_not_all_transitions_added(9).
spec_not_all_transitions_added(10).
spec_not_all_transitions_added(12).
spec_not_all_transitions_added(14).
spec_not_all_transitions_added(20).
spec_not_all_transitions_added(21).
spec_not_all_transitions_added(23).
spec_not_all_transitions_added(25).
spec_max_reached_for_node(_) :-
        fail.
spec_completely_explored :-
        fail.
