spec_trans(root,'$initialise_machine',0).
spec_trans(0,'insert(INDEX1,ITEM1)',1).
spec_trans(0,'insert(INDEX1,ITEM2)',2).
spec_trans(0,'insert(INDEX2,ITEM1)',3).
spec_trans(0,'insert(INDEX2,ITEM2)',4).
spec_trans(0,'remove(INDEX1)',0).
spec_trans(0,'remove(INDEX2)',0).
spec_trans(1,'insert(INDEX1,ITEM1)',1).
spec_trans(1,'insert(INDEX1,ITEM2)',2).
spec_trans(1,'insert(INDEX2,ITEM1)',5).
spec_trans(1,'insert(INDEX2,ITEM2)',6).
spec_trans(1,'remove(INDEX1)',0).
spec_trans(1,'remove(INDEX2)',1).
spec_trans(1,'query(INDEX1)-->ITEM1',1).
spec_trans(4,'insert(INDEX1,ITEM1)',6).
spec_trans(4,'insert(INDEX1,ITEM2)',7).
spec_trans(4,'insert(INDEX2,ITEM1)',3).
spec_trans(4,'insert(INDEX2,ITEM2)',4).
spec_trans(4,'remove(INDEX1)',4).
spec_trans(4,'remove(INDEX2)',0).
spec_trans(4,'query(INDEX2)-->ITEM2',4).
spec_trans(7,'insert(INDEX1,ITEM1)',6).
spec_trans(7,'insert(INDEX1,ITEM2)',7).
spec_trans(7,'insert(INDEX2,ITEM1)',8).
spec_trans(7,'insert(INDEX2,ITEM2)',7).
spec_trans(7,'remove(INDEX1)',4).
spec_trans(7,'remove(INDEX2)',2).
spec_trans(7,'query(INDEX1)-->ITEM2',7).
spec_trans(7,'query(INDEX2)-->ITEM2',7).
spec_trans(2,'insert(INDEX1,ITEM1)',1).
spec_trans(2,'insert(INDEX1,ITEM2)',2).
spec_trans(2,'insert(INDEX2,ITEM1)',8).
spec_trans(2,'insert(INDEX2,ITEM2)',7).
spec_trans(2,'remove(INDEX1)',0).
spec_trans(2,'remove(INDEX2)',2).
spec_trans(2,'query(INDEX1)-->ITEM2',2).
spec_trans(3,'insert(INDEX1,ITEM1)',5).
spec_trans(3,'insert(INDEX1,ITEM2)',8).
spec_trans(3,'insert(INDEX2,ITEM1)',3).
spec_trans(3,'insert(INDEX2,ITEM2)',4).
spec_trans(3,'remove(INDEX1)',3).
spec_trans(3,'remove(INDEX2)',0).
spec_trans(3,'query(INDEX2)-->ITEM1',3).
spec_trans(8,'insert(INDEX1,ITEM1)',5).
spec_trans(8,'insert(INDEX1,ITEM2)',8).
spec_trans(8,'insert(INDEX2,ITEM1)',8).
spec_trans(8,'insert(INDEX2,ITEM2)',7).
spec_trans(8,'remove(INDEX1)',3).
spec_trans(8,'remove(INDEX2)',2).
spec_trans(8,'query(INDEX1)-->ITEM2',8).
spec_trans(8,'query(INDEX2)-->ITEM1',8).
spec_trans(5,'insert(INDEX1,ITEM1)',5).
spec_trans(5,'insert(INDEX1,ITEM2)',8).
spec_trans(5,'insert(INDEX2,ITEM1)',5).
spec_trans(5,'insert(INDEX2,ITEM2)',6).
spec_trans(5,'remove(INDEX1)',3).
spec_trans(5,'remove(INDEX2)',1).
spec_trans(5,'query(INDEX1)-->ITEM1',5).
spec_trans(5,'query(INDEX2)-->ITEM1',5).
spec_trans(6,'insert(INDEX1,ITEM1)',6).
spec_trans(6,'insert(INDEX1,ITEM2)',7).
spec_trans(6,'insert(INDEX2,ITEM1)',5).
spec_trans(6,'insert(INDEX2,ITEM2)',6).
spec_trans(6,'remove(INDEX1)',4).
spec_trans(6,'remove(INDEX2)',1).
spec_trans(6,'query(INDEX1)-->ITEM1',6).
spec_trans(6,'query(INDEX2)-->ITEM2',6).
spec_not_all_transitions_added(_) :-
        fail.
spec_max_reached_for_node(_) :-
        fail.
spec_completely_explored.
