spec_trans(root,'$initialise_machine',1).
spec_trans(root,'$initialise_machine',2).
spec_trans(root,'$initialise_machine',3).
spec_trans(root,'$initialise_machine',4).
spec_trans(0,'$initialise_machine',1).
spec_trans(0,'$initialise_machine',2).
spec_trans(0,'$initialise_machine',3).
spec_trans(0,'$initialise_machine',4).
spec_trans(1,'substitute(PLAYER1,PLAYER12)',5).
spec_trans(1,'substitute(PLAYER2,PLAYER12)',6).
spec_trans(1,'substitute(PLAYER3,PLAYER12)',7).
spec_trans(1,'substitute(PLAYER4,PLAYER12)',8).
spec_trans(1,'substitute(PLAYER5,PLAYER12)',9).
spec_trans(1,'substitute(PLAYER6,PLAYER12)',10).
spec_trans(1,'substitute(PLAYER7,PLAYER12)',11).
spec_trans(1,'substitute(PLAYER8,PLAYER12)',12).
spec_trans(1,'substitute(PLAYER9,PLAYER12)',4).
spec_trans(1,'substitute(PLAYER10,PLAYER12)',3).
spec_trans(1,'query(PLAYER1)-->in',1).
spec_trans(1,'query(PLAYER2)-->in',1).
spec_trans(1,'query(PLAYER3)-->in',1).
spec_trans(1,'query(PLAYER4)-->in',1).
spec_trans(1,'query(PLAYER5)-->in',1).
spec_trans(1,'query(PLAYER6)-->in',1).
spec_trans(1,'query(PLAYER7)-->in',1).
spec_trans(1,'query(PLAYER8)-->in',1).
spec_trans(1,'query(PLAYER9)-->in',1).
spec_trans(1,'query(PLAYER10)-->in',1).
spec_trans(4,'substitute(PLAYER1,PLAYER9)',5).
spec_trans(4,'substitute(PLAYER2,PLAYER9)',6).
spec_trans(4,'substitute(PLAYER3,PLAYER9)',7).
spec_trans(4,'substitute(PLAYER4,PLAYER9)',8).
spec_trans(4,'substitute(PLAYER5,PLAYER9)',9).
spec_trans(4,'substitute(PLAYER6,PLAYER9)',10).
spec_trans(4,'substitute(PLAYER7,PLAYER9)',11).
spec_trans(4,'substitute(PLAYER8,PLAYER9)',12).
spec_trans(4,'substitute(PLAYER10,PLAYER9)',3).
spec_trans(4,'substitute(PLAYER11,PLAYER9)',2).
spec_trans(4,'query(PLAYER1)-->in',4).
spec_trans(4,'query(PLAYER2)-->in',4).
spec_trans(4,'query(PLAYER3)-->in',4).
spec_trans(4,'query(PLAYER4)-->in',4).
spec_trans(4,'query(PLAYER5)-->in',4).
spec_trans(4,'query(PLAYER6)-->in',4).
spec_trans(4,'query(PLAYER7)-->in',4).
spec_trans(4,'query(PLAYER8)-->in',4).
spec_trans(4,'query(PLAYER9)-->out',4).
spec_trans(4,'query(PLAYER10)-->in',4).
spec_trans(2,'substitute(PLAYER1,PLAYER11)',5).
spec_trans(2,'substitute(PLAYER2,PLAYER11)',6).
spec_trans(2,'substitute(PLAYER3,PLAYER11)',7).
spec_trans(2,'substitute(PLAYER4,PLAYER11)',8).
spec_trans(2,'substitute(PLAYER5,PLAYER11)',9).
spec_trans(2,'substitute(PLAYER6,PLAYER11)',10).
spec_trans(2,'substitute(PLAYER7,PLAYER11)',11).
spec_trans(2,'substitute(PLAYER8,PLAYER11)',12).
spec_trans(2,'substitute(PLAYER9,PLAYER11)',4).
spec_trans(2,'substitute(PLAYER10,PLAYER11)',3).
spec_trans(2,'query(PLAYER1)-->in',2).
spec_trans(2,'query(PLAYER2)-->in',2).
spec_trans(2,'query(PLAYER3)-->in',2).
spec_trans(2,'query(PLAYER4)-->in',2).
spec_trans(2,'query(PLAYER5)-->in',2).
spec_trans(2,'query(PLAYER6)-->in',2).
spec_trans(2,'query(PLAYER7)-->in',2).
spec_trans(2,'query(PLAYER8)-->in',2).
spec_trans(2,'query(PLAYER9)-->in',2).
spec_trans(2,'query(PLAYER10)-->in',2).
spec_trans(3,'substitute(PLAYER1,PLAYER10)',5).
spec_trans(3,'substitute(PLAYER2,PLAYER10)',6).
spec_trans(3,'substitute(PLAYER3,PLAYER10)',7).
spec_trans(3,'substitute(PLAYER4,PLAYER10)',8).
spec_trans(3,'substitute(PLAYER5,PLAYER10)',9).
spec_trans(3,'substitute(PLAYER6,PLAYER10)',10).
spec_trans(3,'substitute(PLAYER7,PLAYER10)',11).
spec_trans(3,'substitute(PLAYER8,PLAYER10)',12).
spec_trans(3,'substitute(PLAYER9,PLAYER10)',4).
spec_trans(3,'substitute(PLAYER11,PLAYER10)',2).
spec_trans(3,'query(PLAYER1)-->in',3).
spec_trans(3,'query(PLAYER2)-->in',3).
spec_trans(3,'query(PLAYER3)-->in',3).
spec_trans(3,'query(PLAYER4)-->in',3).
spec_trans(3,'query(PLAYER5)-->in',3).
spec_trans(3,'query(PLAYER6)-->in',3).
spec_trans(3,'query(PLAYER7)-->in',3).
spec_trans(3,'query(PLAYER8)-->in',3).
spec_trans(3,'query(PLAYER9)-->in',3).
spec_trans(3,'query(PLAYER10)-->out',3).
spec_trans(5,'substitute(PLAYER2,PLAYER1)',6).
spec_trans(5,'substitute(PLAYER3,PLAYER1)',7).
spec_trans(5,'substitute(PLAYER4,PLAYER1)',8).
spec_trans(5,'substitute(PLAYER5,PLAYER1)',9).
spec_trans(5,'substitute(PLAYER6,PLAYER1)',10).
spec_trans(5,'substitute(PLAYER7,PLAYER1)',11).
spec_trans(5,'substitute(PLAYER8,PLAYER1)',12).
spec_trans(5,'substitute(PLAYER9,PLAYER1)',4).
spec_trans(5,'substitute(PLAYER10,PLAYER1)',3).
spec_trans(5,'substitute(PLAYER11,PLAYER1)',2).
spec_trans(5,'query(PLAYER1)-->out',5).
spec_trans(5,'query(PLAYER2)-->in',5).
spec_trans(5,'query(PLAYER3)-->in',5).
spec_trans(5,'query(PLAYER4)-->in',5).
spec_trans(5,'query(PLAYER5)-->in',5).
spec_trans(5,'query(PLAYER6)-->in',5).
spec_trans(5,'query(PLAYER7)-->in',5).
spec_trans(5,'query(PLAYER8)-->in',5).
spec_trans(5,'query(PLAYER9)-->in',5).
spec_trans(5,'query(PLAYER10)-->in',5).
spec_trans(6,'substitute(PLAYER1,PLAYER2)',5).
spec_trans(6,'substitute(PLAYER3,PLAYER2)',7).
spec_trans(6,'substitute(PLAYER4,PLAYER2)',8).
spec_trans(6,'substitute(PLAYER5,PLAYER2)',9).
spec_trans(6,'substitute(PLAYER6,PLAYER2)',10).
spec_trans(6,'substitute(PLAYER7,PLAYER2)',11).
spec_trans(6,'substitute(PLAYER8,PLAYER2)',12).
spec_trans(6,'substitute(PLAYER9,PLAYER2)',4).
spec_trans(6,'substitute(PLAYER10,PLAYER2)',3).
spec_trans(6,'substitute(PLAYER11,PLAYER2)',2).
spec_trans(6,'query(PLAYER1)-->in',6).
spec_trans(6,'query(PLAYER2)-->out',6).
spec_trans(6,'query(PLAYER3)-->in',6).
spec_trans(6,'query(PLAYER4)-->in',6).
spec_trans(6,'query(PLAYER5)-->in',6).
spec_trans(6,'query(PLAYER6)-->in',6).
spec_trans(6,'query(PLAYER7)-->in',6).
spec_trans(6,'query(PLAYER8)-->in',6).
spec_trans(6,'query(PLAYER9)-->in',6).
spec_trans(6,'query(PLAYER10)-->in',6).
spec_trans(7,'substitute(PLAYER1,PLAYER3)',5).
spec_trans(7,'substitute(PLAYER2,PLAYER3)',6).
spec_trans(7,'substitute(PLAYER4,PLAYER3)',8).
spec_trans(7,'substitute(PLAYER5,PLAYER3)',9).
spec_trans(7,'substitute(PLAYER6,PLAYER3)',10).
spec_trans(7,'substitute(PLAYER7,PLAYER3)',11).
spec_trans(7,'substitute(PLAYER8,PLAYER3)',12).
spec_trans(7,'substitute(PLAYER9,PLAYER3)',4).
spec_trans(7,'substitute(PLAYER10,PLAYER3)',3).
spec_trans(7,'substitute(PLAYER11,PLAYER3)',2).
spec_trans(7,'query(PLAYER1)-->in',7).
spec_trans(7,'query(PLAYER2)-->in',7).
spec_trans(7,'query(PLAYER3)-->out',7).
spec_trans(7,'query(PLAYER4)-->in',7).
spec_trans(7,'query(PLAYER5)-->in',7).
spec_trans(7,'query(PLAYER6)-->in',7).
spec_trans(7,'query(PLAYER7)-->in',7).
spec_trans(7,'query(PLAYER8)-->in',7).
spec_trans(7,'query(PLAYER9)-->in',7).
spec_trans(7,'query(PLAYER10)-->in',7).
spec_trans(8,'substitute(PLAYER1,PLAYER4)',5).
spec_trans(8,'substitute(PLAYER2,PLAYER4)',6).
spec_trans(8,'substitute(PLAYER3,PLAYER4)',7).
spec_trans(8,'substitute(PLAYER5,PLAYER4)',9).
spec_trans(8,'substitute(PLAYER6,PLAYER4)',10).
spec_trans(8,'substitute(PLAYER7,PLAYER4)',11).
spec_trans(8,'substitute(PLAYER8,PLAYER4)',12).
spec_trans(8,'substitute(PLAYER9,PLAYER4)',4).
spec_trans(8,'substitute(PLAYER10,PLAYER4)',3).
spec_trans(8,'substitute(PLAYER11,PLAYER4)',2).
spec_trans(8,'query(PLAYER1)-->in',8).
spec_trans(8,'query(PLAYER2)-->in',8).
spec_trans(8,'query(PLAYER3)-->in',8).
spec_trans(8,'query(PLAYER4)-->out',8).
spec_trans(8,'query(PLAYER5)-->in',8).
spec_trans(8,'query(PLAYER6)-->in',8).
spec_trans(8,'query(PLAYER7)-->in',8).
spec_trans(8,'query(PLAYER8)-->in',8).
spec_trans(8,'query(PLAYER9)-->in',8).
spec_trans(8,'query(PLAYER10)-->in',8).
spec_trans(9,'substitute(PLAYER1,PLAYER5)',5).
spec_trans(9,'substitute(PLAYER2,PLAYER5)',6).
spec_trans(9,'substitute(PLAYER3,PLAYER5)',7).
spec_trans(9,'substitute(PLAYER4,PLAYER5)',8).
spec_trans(9,'substitute(PLAYER6,PLAYER5)',10).
spec_trans(9,'substitute(PLAYER7,PLAYER5)',11).
spec_trans(9,'substitute(PLAYER8,PLAYER5)',12).
spec_trans(9,'substitute(PLAYER9,PLAYER5)',4).
spec_trans(9,'substitute(PLAYER10,PLAYER5)',3).
spec_trans(9,'substitute(PLAYER11,PLAYER5)',2).
spec_trans(9,'query(PLAYER1)-->in',9).
spec_trans(9,'query(PLAYER2)-->in',9).
spec_trans(9,'query(PLAYER3)-->in',9).
spec_trans(9,'query(PLAYER4)-->in',9).
spec_trans(9,'query(PLAYER5)-->out',9).
spec_trans(9,'query(PLAYER6)-->in',9).
spec_trans(9,'query(PLAYER7)-->in',9).
spec_trans(9,'query(PLAYER8)-->in',9).
spec_trans(9,'query(PLAYER9)-->in',9).
spec_trans(9,'query(PLAYER10)-->in',9).
spec_trans(10,'substitute(PLAYER1,PLAYER6)',5).
spec_trans(10,'substitute(PLAYER2,PLAYER6)',6).
spec_trans(10,'substitute(PLAYER3,PLAYER6)',7).
spec_trans(10,'substitute(PLAYER4,PLAYER6)',8).
spec_trans(10,'substitute(PLAYER5,PLAYER6)',9).
spec_trans(10,'substitute(PLAYER7,PLAYER6)',11).
spec_trans(10,'substitute(PLAYER8,PLAYER6)',12).
spec_trans(10,'substitute(PLAYER9,PLAYER6)',4).
spec_trans(10,'substitute(PLAYER10,PLAYER6)',3).
spec_trans(10,'substitute(PLAYER11,PLAYER6)',2).
spec_trans(10,'query(PLAYER1)-->in',10).
spec_trans(10,'query(PLAYER2)-->in',10).
spec_trans(10,'query(PLAYER3)-->in',10).
spec_trans(10,'query(PLAYER4)-->in',10).
spec_trans(10,'query(PLAYER5)-->in',10).
spec_trans(10,'query(PLAYER6)-->out',10).
spec_trans(10,'query(PLAYER7)-->in',10).
spec_trans(10,'query(PLAYER8)-->in',10).
spec_trans(10,'query(PLAYER9)-->in',10).
spec_trans(10,'query(PLAYER10)-->in',10).
spec_trans(11,'substitute(PLAYER1,PLAYER7)',5).
spec_trans(11,'substitute(PLAYER2,PLAYER7)',6).
spec_trans(11,'substitute(PLAYER3,PLAYER7)',7).
spec_trans(11,'substitute(PLAYER4,PLAYER7)',8).
spec_trans(11,'substitute(PLAYER5,PLAYER7)',9).
spec_trans(11,'substitute(PLAYER6,PLAYER7)',10).
spec_trans(11,'substitute(PLAYER8,PLAYER7)',12).
spec_trans(11,'substitute(PLAYER9,PLAYER7)',4).
spec_trans(11,'substitute(PLAYER10,PLAYER7)',3).
spec_trans(11,'substitute(PLAYER11,PLAYER7)',2).
spec_trans(11,'query(PLAYER1)-->in',11).
spec_trans(11,'query(PLAYER2)-->in',11).
spec_trans(11,'query(PLAYER3)-->in',11).
spec_trans(11,'query(PLAYER4)-->in',11).
spec_trans(11,'query(PLAYER5)-->in',11).
spec_trans(11,'query(PLAYER6)-->in',11).
spec_trans(11,'query(PLAYER7)-->out',11).
spec_trans(11,'query(PLAYER8)-->in',11).
spec_trans(11,'query(PLAYER9)-->in',11).
spec_trans(11,'query(PLAYER10)-->in',11).
spec_trans(12,'substitute(PLAYER1,PLAYER8)',5).
spec_trans(12,'substitute(PLAYER2,PLAYER8)',6).
spec_trans(12,'substitute(PLAYER3,PLAYER8)',7).
spec_trans(12,'substitute(PLAYER4,PLAYER8)',8).
spec_trans(12,'substitute(PLAYER5,PLAYER8)',9).
spec_trans(12,'substitute(PLAYER6,PLAYER8)',10).
spec_trans(12,'substitute(PLAYER7,PLAYER8)',11).
spec_trans(12,'substitute(PLAYER9,PLAYER8)',4).
spec_trans(12,'substitute(PLAYER10,PLAYER8)',3).
spec_trans(12,'substitute(PLAYER11,PLAYER8)',2).
spec_trans(12,'query(PLAYER1)-->in',12).
spec_trans(12,'query(PLAYER2)-->in',12).
spec_trans(12,'query(PLAYER3)-->in',12).
spec_trans(12,'query(PLAYER4)-->in',12).
spec_trans(12,'query(PLAYER5)-->in',12).
spec_trans(12,'query(PLAYER6)-->in',12).
spec_trans(12,'query(PLAYER7)-->in',12).
spec_trans(12,'query(PLAYER8)-->out',12).
spec_trans(12,'query(PLAYER9)-->in',12).
spec_trans(12,'query(PLAYER10)-->in',12).
spec_max_reached_for_node(0).
spec_max_reached_for_node(1).
spec_max_reached_for_node(4).
spec_max_reached_for_node(2).
spec_max_reached_for_node(3).
spec_max_reached_for_node(5).
spec_max_reached_for_node(6).
spec_max_reached_for_node(7).
spec_max_reached_for_node(8).
spec_max_reached_for_node(9).
spec_max_reached_for_node(10).
spec_max_reached_for_node(11).
spec_max_reached_for_node(12).
spec_not_all_transitions_added(_) :-
        fail.
spec_completely_explored :-
        fail.
