spec_trans(root,'$initialise_machine',5).
spec_trans(root,'$initialise_machine',9).
spec_trans(root,'$initialise_machine',10).
spec_trans(root,'$initialise_machine',4).
spec_trans(3,'$initialise_machine',4).
spec_trans(0,'$initialise_machine',5).
spec_trans(4,'rename_VAL_NVAR-->0',4).
spec_trans(4,'rename_STO_NVAR(0)',4).
spec_trans(4,'rename_STO_NVAR(1)',6).
spec_trans(4,'rename_STO_NVAR(2)',7).
spec_trans(4,'rename_STO_NVAR(3)',8).
spec_trans(4,'rename_MIN_NVAR(0)-->0',4).
spec_trans(4,'rename_MIN_NVAR(1)-->0',4).
spec_trans(4,'rename_MIN_NVAR(2)-->0',4).
spec_trans(4,'rename_MIN_NVAR(3)-->0',4).
spec_trans(4,'rename_MAX_NVAR(0)-->0',4).
spec_trans(4,'rename_MAX_NVAR(1)-->1',4).
spec_trans(4,'rename_MAX_NVAR(2)-->2',4).
spec_trans(4,'rename_MAX_NVAR(3)-->3',4).
spec_trans(4,'rename_PRE_INC_NVAR-->TRUE',4).
spec_trans(4,rename_INC_NVAR,6).
spec_trans(4,'rename_PRE_DEC_NVAR-->FALSE',4).
spec_trans(4,'rename_PRE_ADD_NVAR(0)-->TRUE',4).
spec_trans(4,'rename_PRE_ADD_NVAR(1)-->TRUE',4).
spec_trans(4,'rename_PRE_ADD_NVAR(2)-->TRUE',4).
spec_trans(4,'rename_PRE_ADD_NVAR(3)-->TRUE',4).
spec_trans(4,'rename_ADD_NVAR(0)',4).
spec_trans(4,'rename_ADD_NVAR(1)',6).
spec_trans(4,'rename_ADD_NVAR(2)',7).
spec_trans(4,'rename_ADD_NVAR(3)',8).
spec_trans(4,'rename_PRE_MUL_NVAR(0)-->TRUE',4).
spec_trans(4,'rename_PRE_MUL_NVAR(1)-->TRUE',4).
spec_trans(4,'rename_PRE_MUL_NVAR(2)-->TRUE',4).
spec_trans(4,'rename_PRE_MUL_NVAR(3)-->TRUE',4).
spec_trans(4,'rename_MUL_NVAR(0)',4).
spec_trans(4,'rename_MUL_NVAR(1)',4).
spec_trans(4,'rename_MUL_NVAR(2)',4).
spec_trans(4,'rename_MUL_NVAR(3)',4).
spec_trans(4,'rename_PRE_SUB_NVAR(0)-->TRUE',4).
spec_trans(4,'rename_PRE_SUB_NVAR(1)-->FALSE',4).
spec_trans(4,'rename_PRE_SUB_NVAR(2)-->FALSE',4).
spec_trans(4,'rename_PRE_SUB_NVAR(3)-->FALSE',4).
spec_trans(4,'rename_SUB_NVAR(0)',4).
spec_trans(4,'rename_PRE_DIV_NVAR(0)-->FALSE',4).
spec_trans(4,'rename_PRE_DIV_NVAR(1)-->TRUE',4).
spec_trans(4,'rename_PRE_DIV_NVAR(2)-->TRUE',4).
spec_trans(4,'rename_PRE_DIV_NVAR(3)-->TRUE',4).
spec_trans(4,'rename_DIV_NVAR(1)',4).
spec_trans(4,'rename_DIV_NVAR(2)',4).
spec_trans(4,'rename_DIV_NVAR(3)',4).
spec_trans(4,'rename_PRE_MOD_NVAR(0)-->FALSE',4).
spec_trans(4,'rename_PRE_MOD_NVAR(1)-->TRUE',4).
spec_trans(4,'rename_PRE_MOD_NVAR(2)-->TRUE',4).
spec_trans(4,'rename_PRE_MOD_NVAR(3)-->TRUE',4).
spec_trans(4,'rename_MOD_NVAR(1)',4).
spec_trans(4,'rename_MOD_NVAR(2)',4).
spec_trans(4,'rename_MOD_NVAR(3)',4).
spec_trans(4,'rename_EQL_NVAR(0)-->TRUE',4).
spec_trans(4,'rename_EQL_NVAR(1)-->FALSE',4).
spec_trans(4,'rename_EQL_NVAR(2)-->FALSE',4).
spec_trans(4,'rename_EQL_NVAR(3)-->FALSE',4).
spec_trans(4,'rename_NEQ_NVAR(0)-->FALSE',4).
spec_trans(4,'rename_NEQ_NVAR(1)-->TRUE',4).
spec_trans(4,'rename_NEQ_NVAR(2)-->TRUE',4).
spec_trans(4,'rename_NEQ_NVAR(3)-->TRUE',4).
spec_trans(4,'rename_GTR_NVAR(0)-->FALSE',4).
spec_trans(4,'rename_GTR_NVAR(1)-->FALSE',4).
spec_trans(4,'rename_GTR_NVAR(2)-->FALSE',4).
spec_trans(4,'rename_GTR_NVAR(3)-->FALSE',4).
spec_trans(4,'rename_GEQ_NVAR(0)-->TRUE',4).
spec_trans(4,'rename_GEQ_NVAR(1)-->FALSE',4).
spec_trans(4,'rename_GEQ_NVAR(2)-->FALSE',4).
spec_trans(4,'rename_GEQ_NVAR(3)-->FALSE',4).
spec_trans(4,'rename_SMR_NVAR(0)-->FALSE',4).
spec_trans(4,'rename_SMR_NVAR(1)-->TRUE',4).
spec_trans(4,'rename_SMR_NVAR(2)-->TRUE',4).
spec_trans(4,'rename_SMR_NVAR(3)-->TRUE',4).
spec_trans(4,'rename_LEQ_NVAR(0)-->TRUE',4).
spec_trans(4,'rename_LEQ_NVAR(1)-->TRUE',4).
spec_trans(4,'rename_LEQ_NVAR(2)-->TRUE',4).
spec_trans(4,'rename_LEQ_NVAR(3)-->TRUE',4).
spec_trans(4,rename_SAV_NVAR,4).
spec_trans(4,rename_RST_NVAR,4).
spec_trans(4,rename_RST_NVAR,6).
spec_trans(4,rename_RST_NVAR,7).
spec_trans(4,rename_RST_NVAR,8).
spec_trans(4,rename_SAVN_NVAR,4).
spec_trans(4,rename_RSTN_NVAR,4).
spec_trans(4,rename_RSTN_NVAR,6).
spec_trans(4,rename_RSTN_NVAR,7).
spec_trans(4,rename_RSTN_NVAR,8).
spec_trans(8,'rename_VAL_NVAR-->3',8).
spec_trans(8,'rename_STO_NVAR(0)',4).
spec_trans(8,'rename_STO_NVAR(1)',6).
spec_trans(8,'rename_STO_NVAR(2)',7).
spec_trans(8,'rename_STO_NVAR(3)',8).
spec_trans(8,'rename_MIN_NVAR(0)-->0',8).
spec_trans(8,'rename_MIN_NVAR(1)-->1',8).
spec_trans(8,'rename_MIN_NVAR(2)-->2',8).
spec_trans(8,'rename_MIN_NVAR(3)-->3',8).
spec_trans(8,'rename_MAX_NVAR(0)-->3',8).
spec_trans(8,'rename_MAX_NVAR(1)-->3',8).
spec_trans(8,'rename_MAX_NVAR(2)-->3',8).
spec_trans(8,'rename_MAX_NVAR(3)-->3',8).
spec_trans(8,'rename_PRE_INC_NVAR-->FALSE',8).
spec_trans(8,'rename_PRE_DEC_NVAR-->TRUE',8).
spec_trans(8,rename_DEC_NVAR,7).
spec_trans(8,'rename_PRE_ADD_NVAR(0)-->TRUE',8).
spec_trans(8,'rename_PRE_ADD_NVAR(1)-->FALSE',8).
spec_trans(8,'rename_PRE_ADD_NVAR(2)-->FALSE',8).
spec_trans(8,'rename_PRE_ADD_NVAR(3)-->FALSE',8).
spec_trans(8,'rename_ADD_NVAR(0)',8).
spec_trans(8,'rename_PRE_MUL_NVAR(0)-->TRUE',8).
spec_trans(8,'rename_PRE_MUL_NVAR(1)-->TRUE',8).
spec_trans(8,'rename_PRE_MUL_NVAR(2)-->FALSE',8).
spec_trans(8,'rename_PRE_MUL_NVAR(3)-->FALSE',8).
spec_trans(8,'rename_MUL_NVAR(0)',4).
spec_trans(8,'rename_MUL_NVAR(1)',8).
spec_trans(8,'rename_PRE_SUB_NVAR(0)-->TRUE',8).
spec_trans(8,'rename_PRE_SUB_NVAR(1)-->TRUE',8).
spec_trans(8,'rename_PRE_SUB_NVAR(2)-->TRUE',8).
spec_trans(8,'rename_PRE_SUB_NVAR(3)-->TRUE',8).
spec_trans(8,'rename_SUB_NVAR(0)',8).
spec_trans(8,'rename_SUB_NVAR(1)',7).
spec_trans(8,'rename_SUB_NVAR(2)',6).
spec_trans(8,'rename_SUB_NVAR(3)',4).
spec_trans(8,'rename_PRE_DIV_NVAR(0)-->FALSE',8).
spec_trans(8,'rename_PRE_DIV_NVAR(1)-->TRUE',8).
spec_trans(8,'rename_PRE_DIV_NVAR(2)-->TRUE',8).
spec_trans(8,'rename_PRE_DIV_NVAR(3)-->TRUE',8).
spec_trans(8,'rename_DIV_NVAR(1)',8).
spec_trans(8,'rename_DIV_NVAR(2)',6).
spec_trans(8,'rename_DIV_NVAR(3)',6).
spec_trans(8,'rename_PRE_MOD_NVAR(0)-->FALSE',8).
spec_trans(8,'rename_PRE_MOD_NVAR(1)-->TRUE',8).
spec_trans(8,'rename_PRE_MOD_NVAR(2)-->TRUE',8).
spec_trans(8,'rename_PRE_MOD_NVAR(3)-->TRUE',8).
spec_trans(8,'rename_MOD_NVAR(1)',4).
spec_trans(8,'rename_MOD_NVAR(2)',6).
spec_trans(8,'rename_MOD_NVAR(3)',4).
spec_trans(8,'rename_EQL_NVAR(0)-->FALSE',8).
spec_trans(8,'rename_EQL_NVAR(1)-->FALSE',8).
spec_trans(8,'rename_EQL_NVAR(2)-->FALSE',8).
spec_trans(8,'rename_EQL_NVAR(3)-->TRUE',8).
spec_trans(8,'rename_NEQ_NVAR(0)-->TRUE',8).
spec_trans(8,'rename_NEQ_NVAR(1)-->TRUE',8).
spec_trans(8,'rename_NEQ_NVAR(2)-->TRUE',8).
spec_trans(8,'rename_NEQ_NVAR(3)-->FALSE',8).
spec_trans(8,'rename_GTR_NVAR(0)-->TRUE',8).
spec_trans(8,'rename_GTR_NVAR(1)-->TRUE',8).
spec_trans(8,'rename_GTR_NVAR(2)-->TRUE',8).
spec_trans(8,'rename_GTR_NVAR(3)-->FALSE',8).
spec_trans(8,'rename_GEQ_NVAR(0)-->TRUE',8).
spec_trans(8,'rename_GEQ_NVAR(1)-->TRUE',8).
spec_trans(8,'rename_GEQ_NVAR(2)-->TRUE',8).
spec_trans(8,'rename_GEQ_NVAR(3)-->TRUE',8).
spec_trans(8,'rename_SMR_NVAR(0)-->FALSE',8).
spec_trans(8,'rename_SMR_NVAR(1)-->FALSE',8).
spec_trans(8,'rename_SMR_NVAR(2)-->FALSE',8).
spec_trans(8,'rename_SMR_NVAR(3)-->FALSE',8).
spec_trans(8,'rename_LEQ_NVAR(0)-->FALSE',8).
spec_trans(8,'rename_LEQ_NVAR(1)-->FALSE',8).
spec_trans(8,'rename_LEQ_NVAR(2)-->FALSE',8).
spec_trans(8,'rename_LEQ_NVAR(3)-->TRUE',8).
spec_trans(8,rename_SAV_NVAR,8).
spec_trans(8,rename_RST_NVAR,4).
spec_trans(8,rename_RST_NVAR,6).
spec_trans(8,rename_RST_NVAR,7).
spec_trans(8,rename_RST_NVAR,8).
spec_trans(8,rename_SAVN_NVAR,8).
spec_trans(8,rename_RSTN_NVAR,4).
spec_trans(8,rename_RSTN_NVAR,6).
spec_trans(8,rename_RSTN_NVAR,7).
spec_trans(8,rename_RSTN_NVAR,8).
spec_trans(7,'rename_VAL_NVAR-->2',7).
spec_trans(7,'rename_STO_NVAR(0)',4).
spec_trans(7,'rename_STO_NVAR(1)',6).
spec_trans(7,'rename_STO_NVAR(2)',7).
spec_trans(7,'rename_STO_NVAR(3)',8).
spec_trans(7,'rename_MIN_NVAR(0)-->0',7).
spec_trans(7,'rename_MIN_NVAR(1)-->1',7).
spec_trans(7,'rename_MIN_NVAR(2)-->2',7).
spec_trans(7,'rename_MIN_NVAR(3)-->2',7).
spec_trans(7,'rename_MAX_NVAR(0)-->2',7).
spec_trans(7,'rename_MAX_NVAR(1)-->2',7).
spec_trans(7,'rename_MAX_NVAR(2)-->2',7).
spec_trans(7,'rename_MAX_NVAR(3)-->3',7).
spec_trans(7,'rename_PRE_INC_NVAR-->TRUE',7).
spec_trans(7,rename_INC_NVAR,8).
spec_trans(7,'rename_PRE_DEC_NVAR-->TRUE',7).
spec_trans(7,rename_DEC_NVAR,6).
spec_trans(7,'rename_PRE_ADD_NVAR(0)-->TRUE',7).
spec_trans(7,'rename_PRE_ADD_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_PRE_ADD_NVAR(2)-->FALSE',7).
spec_trans(7,'rename_PRE_ADD_NVAR(3)-->FALSE',7).
spec_trans(7,'rename_ADD_NVAR(0)',7).
spec_trans(7,'rename_ADD_NVAR(1)',8).
spec_trans(7,'rename_PRE_MUL_NVAR(0)-->TRUE',7).
spec_trans(7,'rename_PRE_MUL_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_PRE_MUL_NVAR(2)-->FALSE',7).
spec_trans(7,'rename_PRE_MUL_NVAR(3)-->FALSE',7).
spec_trans(7,'rename_MUL_NVAR(0)',4).
spec_trans(7,'rename_MUL_NVAR(1)',7).
spec_trans(7,'rename_PRE_SUB_NVAR(0)-->TRUE',7).
spec_trans(7,'rename_PRE_SUB_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_PRE_SUB_NVAR(2)-->TRUE',7).
spec_trans(7,'rename_PRE_SUB_NVAR(3)-->FALSE',7).
spec_trans(7,'rename_SUB_NVAR(0)',7).
spec_trans(7,'rename_SUB_NVAR(1)',6).
spec_trans(7,'rename_SUB_NVAR(2)',4).
spec_trans(7,'rename_PRE_DIV_NVAR(0)-->FALSE',7).
spec_trans(7,'rename_PRE_DIV_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_PRE_DIV_NVAR(2)-->TRUE',7).
spec_trans(7,'rename_PRE_DIV_NVAR(3)-->TRUE',7).
spec_trans(7,'rename_DIV_NVAR(1)',7).
spec_trans(7,'rename_DIV_NVAR(2)',6).
spec_trans(7,'rename_DIV_NVAR(3)',4).
spec_trans(7,'rename_PRE_MOD_NVAR(0)-->FALSE',7).
spec_trans(7,'rename_PRE_MOD_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_PRE_MOD_NVAR(2)-->TRUE',7).
spec_trans(7,'rename_PRE_MOD_NVAR(3)-->TRUE',7).
spec_trans(7,'rename_MOD_NVAR(1)',4).
spec_trans(7,'rename_MOD_NVAR(2)',4).
spec_trans(7,'rename_MOD_NVAR(3)',7).
spec_trans(7,'rename_EQL_NVAR(0)-->FALSE',7).
spec_trans(7,'rename_EQL_NVAR(1)-->FALSE',7).
spec_trans(7,'rename_EQL_NVAR(2)-->TRUE',7).
spec_trans(7,'rename_EQL_NVAR(3)-->FALSE',7).
spec_trans(7,'rename_NEQ_NVAR(0)-->TRUE',7).
spec_trans(7,'rename_NEQ_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_NEQ_NVAR(2)-->FALSE',7).
spec_trans(7,'rename_NEQ_NVAR(3)-->TRUE',7).
spec_trans(7,'rename_GTR_NVAR(0)-->TRUE',7).
spec_trans(7,'rename_GTR_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_GTR_NVAR(2)-->FALSE',7).
spec_trans(7,'rename_GTR_NVAR(3)-->FALSE',7).
spec_trans(7,'rename_GEQ_NVAR(0)-->TRUE',7).
spec_trans(7,'rename_GEQ_NVAR(1)-->TRUE',7).
spec_trans(7,'rename_GEQ_NVAR(2)-->TRUE',7).
spec_trans(7,'rename_GEQ_NVAR(3)-->FALSE',7).
spec_trans(7,'rename_SMR_NVAR(0)-->FALSE',7).
spec_trans(7,'rename_SMR_NVAR(1)-->FALSE',7).
spec_trans(7,'rename_SMR_NVAR(2)-->FALSE',7).
spec_trans(7,'rename_SMR_NVAR(3)-->TRUE',7).
spec_trans(7,'rename_LEQ_NVAR(0)-->FALSE',7).
spec_trans(7,'rename_LEQ_NVAR(1)-->FALSE',7).
spec_trans(7,'rename_LEQ_NVAR(2)-->TRUE',7).
spec_trans(7,'rename_LEQ_NVAR(3)-->TRUE',7).
spec_trans(7,rename_SAV_NVAR,7).
spec_trans(7,rename_RST_NVAR,4).
spec_trans(7,rename_RST_NVAR,6).
spec_trans(7,rename_RST_NVAR,7).
spec_trans(7,rename_RST_NVAR,8).
spec_trans(7,rename_SAVN_NVAR,7).
spec_trans(7,rename_RSTN_NVAR,4).
spec_trans(7,rename_RSTN_NVAR,6).
spec_trans(7,rename_RSTN_NVAR,7).
spec_trans(7,rename_RSTN_NVAR,8).
spec_trans(1,'$initialise_machine',9).
spec_trans(6,'rename_VAL_NVAR-->1',6).
spec_trans(6,'rename_STO_NVAR(0)',4).
spec_trans(6,'rename_STO_NVAR(1)',6).
spec_trans(6,'rename_STO_NVAR(2)',7).
spec_trans(6,'rename_STO_NVAR(3)',8).
spec_trans(6,'rename_MIN_NVAR(0)-->0',6).
spec_trans(6,'rename_MIN_NVAR(1)-->1',6).
spec_trans(6,'rename_MIN_NVAR(2)-->1',6).
spec_trans(6,'rename_MIN_NVAR(3)-->1',6).
spec_trans(6,'rename_MAX_NVAR(0)-->1',6).
spec_trans(6,'rename_MAX_NVAR(1)-->1',6).
spec_trans(6,'rename_MAX_NVAR(2)-->2',6).
spec_trans(6,'rename_MAX_NVAR(3)-->3',6).
spec_trans(6,'rename_PRE_INC_NVAR-->TRUE',6).
spec_trans(6,rename_INC_NVAR,7).
spec_trans(6,'rename_PRE_DEC_NVAR-->TRUE',6).
spec_trans(6,rename_DEC_NVAR,4).
spec_trans(6,'rename_PRE_ADD_NVAR(0)-->TRUE',6).
spec_trans(6,'rename_PRE_ADD_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_PRE_ADD_NVAR(2)-->TRUE',6).
spec_trans(6,'rename_PRE_ADD_NVAR(3)-->FALSE',6).
spec_trans(6,'rename_ADD_NVAR(0)',6).
spec_trans(6,'rename_ADD_NVAR(1)',7).
spec_trans(6,'rename_ADD_NVAR(2)',8).
spec_trans(6,'rename_PRE_MUL_NVAR(0)-->TRUE',6).
spec_trans(6,'rename_PRE_MUL_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_PRE_MUL_NVAR(2)-->TRUE',6).
spec_trans(6,'rename_PRE_MUL_NVAR(3)-->TRUE',6).
spec_trans(6,'rename_MUL_NVAR(0)',4).
spec_trans(6,'rename_MUL_NVAR(1)',6).
spec_trans(6,'rename_MUL_NVAR(2)',7).
spec_trans(6,'rename_MUL_NVAR(3)',8).
spec_trans(6,'rename_PRE_SUB_NVAR(0)-->TRUE',6).
spec_trans(6,'rename_PRE_SUB_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_PRE_SUB_NVAR(2)-->FALSE',6).
spec_trans(6,'rename_PRE_SUB_NVAR(3)-->FALSE',6).
spec_trans(6,'rename_SUB_NVAR(0)',6).
spec_trans(6,'rename_SUB_NVAR(1)',4).
spec_trans(6,'rename_PRE_DIV_NVAR(0)-->FALSE',6).
spec_trans(6,'rename_PRE_DIV_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_PRE_DIV_NVAR(2)-->TRUE',6).
spec_trans(6,'rename_PRE_DIV_NVAR(3)-->TRUE',6).
spec_trans(6,'rename_DIV_NVAR(1)',6).
spec_trans(6,'rename_DIV_NVAR(2)',4).
spec_trans(6,'rename_DIV_NVAR(3)',4).
spec_trans(6,'rename_PRE_MOD_NVAR(0)-->FALSE',6).
spec_trans(6,'rename_PRE_MOD_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_PRE_MOD_NVAR(2)-->TRUE',6).
spec_trans(6,'rename_PRE_MOD_NVAR(3)-->TRUE',6).
spec_trans(6,'rename_MOD_NVAR(1)',4).
spec_trans(6,'rename_MOD_NVAR(2)',6).
spec_trans(6,'rename_MOD_NVAR(3)',6).
spec_trans(6,'rename_EQL_NVAR(0)-->FALSE',6).
spec_trans(6,'rename_EQL_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_EQL_NVAR(2)-->FALSE',6).
spec_trans(6,'rename_EQL_NVAR(3)-->FALSE',6).
spec_trans(6,'rename_NEQ_NVAR(0)-->TRUE',6).
spec_trans(6,'rename_NEQ_NVAR(1)-->FALSE',6).
spec_trans(6,'rename_NEQ_NVAR(2)-->TRUE',6).
spec_trans(6,'rename_NEQ_NVAR(3)-->TRUE',6).
spec_trans(6,'rename_GTR_NVAR(0)-->TRUE',6).
spec_trans(6,'rename_GTR_NVAR(1)-->FALSE',6).
spec_trans(6,'rename_GTR_NVAR(2)-->FALSE',6).
spec_trans(6,'rename_GTR_NVAR(3)-->FALSE',6).
spec_trans(6,'rename_GEQ_NVAR(0)-->TRUE',6).
spec_trans(6,'rename_GEQ_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_GEQ_NVAR(2)-->FALSE',6).
spec_trans(6,'rename_GEQ_NVAR(3)-->FALSE',6).
spec_trans(6,'rename_SMR_NVAR(0)-->FALSE',6).
spec_trans(6,'rename_SMR_NVAR(1)-->FALSE',6).
spec_trans(6,'rename_SMR_NVAR(2)-->TRUE',6).
spec_trans(6,'rename_SMR_NVAR(3)-->TRUE',6).
spec_trans(6,'rename_LEQ_NVAR(0)-->FALSE',6).
spec_trans(6,'rename_LEQ_NVAR(1)-->TRUE',6).
spec_trans(6,'rename_LEQ_NVAR(2)-->TRUE',6).
spec_trans(6,'rename_LEQ_NVAR(3)-->TRUE',6).
spec_trans(6,rename_SAV_NVAR,6).
spec_trans(6,rename_RST_NVAR,4).
spec_trans(6,rename_RST_NVAR,6).
spec_trans(6,rename_RST_NVAR,7).
spec_trans(6,rename_RST_NVAR,8).
spec_trans(6,rename_SAVN_NVAR,6).
spec_trans(6,rename_RSTN_NVAR,4).
spec_trans(6,rename_RSTN_NVAR,6).
spec_trans(6,rename_RSTN_NVAR,7).
spec_trans(6,rename_RSTN_NVAR,8).
spec_trans(2,'$initialise_machine',10).
spec_trans(5,'rename_VAL_NVAR-->0',5).
spec_trans(5,'rename_STO_NVAR(0)',5).
spec_trans(5,'rename_MIN_NVAR(0)-->0',5).
spec_trans(5,'rename_MAX_NVAR(0)-->0',5).
spec_trans(5,'rename_PRE_INC_NVAR-->FALSE',5).
spec_trans(5,'rename_PRE_DEC_NVAR-->FALSE',5).
spec_trans(5,'rename_PRE_ADD_NVAR(0)-->TRUE',5).
spec_trans(5,'rename_ADD_NVAR(0)',5).
spec_trans(5,'rename_PRE_MUL_NVAR(0)-->TRUE',5).
spec_trans(5,'rename_MUL_NVAR(0)',5).
spec_trans(5,'rename_PRE_SUB_NVAR(0)-->TRUE',5).
spec_trans(5,'rename_SUB_NVAR(0)',5).
spec_trans(5,'rename_PRE_DIV_NVAR(0)-->FALSE',5).
spec_trans(5,'rename_PRE_MOD_NVAR(0)-->FALSE',5).
spec_trans(5,'rename_EQL_NVAR(0)-->TRUE',5).
spec_trans(5,'rename_NEQ_NVAR(0)-->FALSE',5).
spec_trans(5,'rename_GTR_NVAR(0)-->FALSE',5).
spec_trans(5,'rename_GEQ_NVAR(0)-->TRUE',5).
spec_trans(5,'rename_SMR_NVAR(0)-->FALSE',5).
spec_trans(5,'rename_LEQ_NVAR(0)-->TRUE',5).
spec_trans(5,rename_SAV_NVAR,5).
spec_trans(5,rename_RST_NVAR,5).
spec_trans(5,rename_SAVN_NVAR,5).
spec_trans(5,rename_RSTN_NVAR,5).
spec_trans(9,'rename_VAL_NVAR-->0',9).
spec_trans(9,'rename_STO_NVAR(0)',9).
spec_trans(9,'rename_STO_NVAR(1)',11).
spec_trans(9,'rename_MIN_NVAR(0)-->0',9).
spec_trans(9,'rename_MIN_NVAR(1)-->0',9).
spec_trans(9,'rename_MAX_NVAR(0)-->0',9).
spec_trans(9,'rename_MAX_NVAR(1)-->1',9).
spec_trans(9,'rename_PRE_INC_NVAR-->TRUE',9).
spec_trans(9,rename_INC_NVAR,11).
spec_trans(9,'rename_PRE_DEC_NVAR-->FALSE',9).
spec_trans(9,'rename_PRE_ADD_NVAR(0)-->TRUE',9).
spec_trans(9,'rename_PRE_ADD_NVAR(1)-->TRUE',9).
spec_trans(9,'rename_ADD_NVAR(0)',9).
spec_trans(9,'rename_ADD_NVAR(1)',11).
spec_trans(9,'rename_PRE_MUL_NVAR(0)-->TRUE',9).
spec_trans(9,'rename_PRE_MUL_NVAR(1)-->TRUE',9).
spec_trans(9,'rename_MUL_NVAR(0)',9).
spec_trans(9,'rename_MUL_NVAR(1)',9).
spec_trans(9,'rename_PRE_SUB_NVAR(0)-->TRUE',9).
spec_trans(9,'rename_PRE_SUB_NVAR(1)-->FALSE',9).
spec_trans(9,'rename_SUB_NVAR(0)',9).
spec_trans(9,'rename_PRE_DIV_NVAR(0)-->FALSE',9).
spec_trans(9,'rename_PRE_DIV_NVAR(1)-->TRUE',9).
spec_trans(9,'rename_DIV_NVAR(1)',9).
spec_trans(9,'rename_PRE_MOD_NVAR(0)-->FALSE',9).
spec_trans(9,'rename_PRE_MOD_NVAR(1)-->TRUE',9).
spec_trans(9,'rename_MOD_NVAR(1)',9).
spec_trans(9,'rename_EQL_NVAR(0)-->TRUE',9).
spec_trans(9,'rename_EQL_NVAR(1)-->FALSE',9).
spec_trans(9,'rename_NEQ_NVAR(0)-->FALSE',9).
spec_trans(9,'rename_NEQ_NVAR(1)-->TRUE',9).
spec_trans(9,'rename_GTR_NVAR(0)-->FALSE',9).
spec_trans(9,'rename_GTR_NVAR(1)-->FALSE',9).
spec_trans(9,'rename_GEQ_NVAR(0)-->TRUE',9).
spec_trans(9,'rename_GEQ_NVAR(1)-->FALSE',9).
spec_trans(9,'rename_SMR_NVAR(0)-->FALSE',9).
spec_trans(9,'rename_SMR_NVAR(1)-->TRUE',9).
spec_trans(9,'rename_LEQ_NVAR(0)-->TRUE',9).
spec_trans(9,'rename_LEQ_NVAR(1)-->TRUE',9).
spec_trans(9,rename_SAV_NVAR,9).
spec_trans(9,rename_RST_NVAR,9).
spec_trans(9,rename_RST_NVAR,11).
spec_trans(9,rename_SAVN_NVAR,9).
spec_trans(9,rename_RSTN_NVAR,9).
spec_trans(9,rename_RSTN_NVAR,11).
spec_trans(10,'rename_VAL_NVAR-->0',10).
spec_trans(10,'rename_STO_NVAR(0)',10).
spec_trans(10,'rename_STO_NVAR(1)',12).
spec_trans(10,'rename_STO_NVAR(2)',13).
spec_trans(10,'rename_MIN_NVAR(0)-->0',10).
spec_trans(10,'rename_MIN_NVAR(1)-->0',10).
spec_trans(10,'rename_MIN_NVAR(2)-->0',10).
spec_trans(10,'rename_MAX_NVAR(0)-->0',10).
spec_trans(10,'rename_MAX_NVAR(1)-->1',10).
spec_trans(10,'rename_MAX_NVAR(2)-->2',10).
spec_trans(10,'rename_PRE_INC_NVAR-->TRUE',10).
spec_trans(10,rename_INC_NVAR,12).
spec_trans(10,'rename_PRE_DEC_NVAR-->FALSE',10).
spec_trans(10,'rename_PRE_ADD_NVAR(0)-->TRUE',10).
spec_trans(10,'rename_PRE_ADD_NVAR(1)-->TRUE',10).
spec_trans(10,'rename_PRE_ADD_NVAR(2)-->TRUE',10).
spec_trans(10,'rename_ADD_NVAR(0)',10).
spec_trans(10,'rename_ADD_NVAR(1)',12).
spec_trans(10,'rename_ADD_NVAR(2)',13).
spec_trans(10,'rename_PRE_MUL_NVAR(0)-->TRUE',10).
spec_trans(10,'rename_PRE_MUL_NVAR(1)-->TRUE',10).
spec_trans(10,'rename_PRE_MUL_NVAR(2)-->TRUE',10).
spec_trans(10,'rename_MUL_NVAR(0)',10).
spec_trans(10,'rename_MUL_NVAR(1)',10).
spec_trans(10,'rename_MUL_NVAR(2)',10).
spec_trans(10,'rename_PRE_SUB_NVAR(0)-->TRUE',10).
spec_trans(10,'rename_PRE_SUB_NVAR(1)-->FALSE',10).
spec_trans(10,'rename_PRE_SUB_NVAR(2)-->FALSE',10).
spec_trans(10,'rename_SUB_NVAR(0)',10).
spec_trans(10,'rename_PRE_DIV_NVAR(0)-->FALSE',10).
spec_trans(10,'rename_PRE_DIV_NVAR(1)-->TRUE',10).
spec_trans(10,'rename_PRE_DIV_NVAR(2)-->TRUE',10).
spec_trans(10,'rename_DIV_NVAR(1)',10).
spec_trans(10,'rename_DIV_NVAR(2)',10).
spec_trans(10,'rename_PRE_MOD_NVAR(0)-->FALSE',10).
spec_trans(10,'rename_PRE_MOD_NVAR(1)-->TRUE',10).
spec_trans(10,'rename_PRE_MOD_NVAR(2)-->TRUE',10).
spec_trans(10,'rename_MOD_NVAR(1)',10).
spec_trans(10,'rename_MOD_NVAR(2)',10).
spec_trans(10,'rename_EQL_NVAR(0)-->TRUE',10).
spec_trans(10,'rename_EQL_NVAR(1)-->FALSE',10).
spec_trans(10,'rename_EQL_NVAR(2)-->FALSE',10).
spec_trans(10,'rename_NEQ_NVAR(0)-->FALSE',10).
spec_trans(10,'rename_NEQ_NVAR(1)-->TRUE',10).
spec_trans(10,'rename_NEQ_NVAR(2)-->TRUE',10).
spec_trans(10,'rename_GTR_NVAR(0)-->FALSE',10).
spec_trans(10,'rename_GTR_NVAR(1)-->FALSE',10).
spec_trans(10,'rename_GTR_NVAR(2)-->FALSE',10).
spec_trans(10,'rename_GEQ_NVAR(0)-->TRUE',10).
spec_trans(10,'rename_GEQ_NVAR(1)-->FALSE',10).
spec_trans(10,'rename_GEQ_NVAR(2)-->FALSE',10).
spec_trans(10,'rename_SMR_NVAR(0)-->FALSE',10).
spec_trans(10,'rename_SMR_NVAR(1)-->TRUE',10).
spec_trans(10,'rename_SMR_NVAR(2)-->TRUE',10).
spec_trans(10,'rename_LEQ_NVAR(0)-->TRUE',10).
spec_trans(10,'rename_LEQ_NVAR(1)-->TRUE',10).
spec_trans(10,'rename_LEQ_NVAR(2)-->TRUE',10).
spec_trans(10,rename_SAV_NVAR,10).
spec_trans(10,rename_RST_NVAR,10).
spec_trans(10,rename_RST_NVAR,12).
spec_trans(10,rename_RST_NVAR,13).
spec_trans(10,rename_SAVN_NVAR,10).
spec_trans(10,rename_RSTN_NVAR,10).
spec_trans(10,rename_RSTN_NVAR,12).
spec_trans(10,rename_RSTN_NVAR,13).
spec_trans(11,'rename_VAL_NVAR-->1',11).
spec_trans(11,'rename_STO_NVAR(0)',9).
spec_trans(11,'rename_STO_NVAR(1)',11).
spec_trans(11,'rename_MIN_NVAR(0)-->0',11).
spec_trans(11,'rename_MIN_NVAR(1)-->1',11).
spec_trans(11,'rename_MAX_NVAR(0)-->1',11).
spec_trans(11,'rename_MAX_NVAR(1)-->1',11).
spec_trans(11,'rename_PRE_INC_NVAR-->FALSE',11).
spec_trans(11,'rename_PRE_DEC_NVAR-->TRUE',11).
spec_trans(11,rename_DEC_NVAR,9).
spec_trans(11,'rename_PRE_ADD_NVAR(0)-->TRUE',11).
spec_trans(11,'rename_PRE_ADD_NVAR(1)-->FALSE',11).
spec_trans(11,'rename_ADD_NVAR(0)',11).
spec_trans(11,'rename_PRE_MUL_NVAR(0)-->TRUE',11).
spec_trans(11,'rename_PRE_MUL_NVAR(1)-->TRUE',11).
spec_trans(11,'rename_MUL_NVAR(0)',9).
spec_trans(11,'rename_MUL_NVAR(1)',11).
spec_trans(11,'rename_PRE_SUB_NVAR(0)-->TRUE',11).
spec_trans(11,'rename_PRE_SUB_NVAR(1)-->TRUE',11).
spec_trans(11,'rename_SUB_NVAR(0)',11).
spec_trans(11,'rename_SUB_NVAR(1)',9).
spec_trans(11,'rename_PRE_DIV_NVAR(0)-->FALSE',11).
spec_trans(11,'rename_PRE_DIV_NVAR(1)-->TRUE',11).
spec_trans(11,'rename_DIV_NVAR(1)',11).
spec_trans(11,'rename_PRE_MOD_NVAR(0)-->FALSE',11).
spec_trans(11,'rename_PRE_MOD_NVAR(1)-->TRUE',11).
spec_trans(11,'rename_MOD_NVAR(1)',9).
spec_trans(11,'rename_EQL_NVAR(0)-->FALSE',11).
spec_trans(11,'rename_EQL_NVAR(1)-->TRUE',11).
spec_trans(11,'rename_NEQ_NVAR(0)-->TRUE',11).
spec_trans(11,'rename_NEQ_NVAR(1)-->FALSE',11).
spec_trans(11,'rename_GTR_NVAR(0)-->TRUE',11).
spec_trans(11,'rename_GTR_NVAR(1)-->FALSE',11).
spec_trans(11,'rename_GEQ_NVAR(0)-->TRUE',11).
spec_trans(11,'rename_GEQ_NVAR(1)-->TRUE',11).
spec_trans(11,'rename_SMR_NVAR(0)-->FALSE',11).
spec_trans(11,'rename_SMR_NVAR(1)-->FALSE',11).
spec_trans(11,'rename_LEQ_NVAR(0)-->FALSE',11).
spec_trans(11,'rename_LEQ_NVAR(1)-->TRUE',11).
spec_trans(11,rename_SAV_NVAR,11).
spec_trans(11,rename_RST_NVAR,9).
spec_trans(11,rename_RST_NVAR,11).
spec_trans(11,rename_SAVN_NVAR,11).
spec_trans(11,rename_RSTN_NVAR,9).
spec_trans(11,rename_RSTN_NVAR,11).
spec_trans(12,'rename_VAL_NVAR-->1',12).
spec_trans(12,'rename_STO_NVAR(0)',10).
spec_trans(12,'rename_STO_NVAR(1)',12).
spec_trans(12,'rename_STO_NVAR(2)',13).
spec_trans(12,'rename_MIN_NVAR(0)-->0',12).
spec_trans(12,'rename_MIN_NVAR(1)-->1',12).
spec_trans(12,'rename_MIN_NVAR(2)-->1',12).
spec_trans(12,'rename_MAX_NVAR(0)-->1',12).
spec_trans(12,'rename_MAX_NVAR(1)-->1',12).
spec_trans(12,'rename_MAX_NVAR(2)-->2',12).
spec_trans(12,'rename_PRE_INC_NVAR-->TRUE',12).
spec_trans(12,rename_INC_NVAR,13).
spec_trans(12,'rename_PRE_DEC_NVAR-->TRUE',12).
spec_trans(12,rename_DEC_NVAR,10).
spec_trans(12,'rename_PRE_ADD_NVAR(0)-->TRUE',12).
spec_trans(12,'rename_PRE_ADD_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_PRE_ADD_NVAR(2)-->FALSE',12).
spec_trans(12,'rename_ADD_NVAR(0)',12).
spec_trans(12,'rename_ADD_NVAR(1)',13).
spec_trans(12,'rename_PRE_MUL_NVAR(0)-->TRUE',12).
spec_trans(12,'rename_PRE_MUL_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_PRE_MUL_NVAR(2)-->TRUE',12).
spec_trans(12,'rename_MUL_NVAR(0)',10).
spec_trans(12,'rename_MUL_NVAR(1)',12).
spec_trans(12,'rename_MUL_NVAR(2)',13).
spec_trans(12,'rename_PRE_SUB_NVAR(0)-->TRUE',12).
spec_trans(12,'rename_PRE_SUB_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_PRE_SUB_NVAR(2)-->FALSE',12).
spec_trans(12,'rename_SUB_NVAR(0)',12).
spec_trans(12,'rename_SUB_NVAR(1)',10).
spec_trans(12,'rename_PRE_DIV_NVAR(0)-->FALSE',12).
spec_trans(12,'rename_PRE_DIV_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_PRE_DIV_NVAR(2)-->TRUE',12).
spec_trans(12,'rename_DIV_NVAR(1)',12).
spec_trans(12,'rename_DIV_NVAR(2)',10).
spec_trans(12,'rename_PRE_MOD_NVAR(0)-->FALSE',12).
spec_trans(12,'rename_PRE_MOD_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_PRE_MOD_NVAR(2)-->TRUE',12).
spec_trans(12,'rename_MOD_NVAR(1)',10).
spec_trans(12,'rename_MOD_NVAR(2)',12).
spec_trans(12,'rename_EQL_NVAR(0)-->FALSE',12).
spec_trans(12,'rename_EQL_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_EQL_NVAR(2)-->FALSE',12).
spec_trans(12,'rename_NEQ_NVAR(0)-->TRUE',12).
spec_trans(12,'rename_NEQ_NVAR(1)-->FALSE',12).
spec_trans(12,'rename_NEQ_NVAR(2)-->TRUE',12).
spec_trans(12,'rename_GTR_NVAR(0)-->TRUE',12).
spec_trans(12,'rename_GTR_NVAR(1)-->FALSE',12).
spec_trans(12,'rename_GTR_NVAR(2)-->FALSE',12).
spec_trans(12,'rename_GEQ_NVAR(0)-->TRUE',12).
spec_trans(12,'rename_GEQ_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_GEQ_NVAR(2)-->FALSE',12).
spec_trans(12,'rename_SMR_NVAR(0)-->FALSE',12).
spec_trans(12,'rename_SMR_NVAR(1)-->FALSE',12).
spec_trans(12,'rename_SMR_NVAR(2)-->TRUE',12).
spec_trans(12,'rename_LEQ_NVAR(0)-->FALSE',12).
spec_trans(12,'rename_LEQ_NVAR(1)-->TRUE',12).
spec_trans(12,'rename_LEQ_NVAR(2)-->TRUE',12).
spec_trans(12,rename_SAV_NVAR,12).
spec_trans(12,rename_RST_NVAR,10).
spec_trans(12,rename_RST_NVAR,12).
spec_trans(12,rename_RST_NVAR,13).
spec_trans(12,rename_SAVN_NVAR,12).
spec_trans(12,rename_RSTN_NVAR,10).
spec_trans(12,rename_RSTN_NVAR,12).
spec_trans(12,rename_RSTN_NVAR,13).
spec_trans(13,'rename_VAL_NVAR-->2',13).
spec_trans(13,'rename_STO_NVAR(0)',10).
spec_trans(13,'rename_STO_NVAR(1)',12).
spec_trans(13,'rename_STO_NVAR(2)',13).
spec_trans(13,'rename_MIN_NVAR(0)-->0',13).
spec_trans(13,'rename_MIN_NVAR(1)-->1',13).
spec_trans(13,'rename_MIN_NVAR(2)-->2',13).
spec_trans(13,'rename_MAX_NVAR(0)-->2',13).
spec_trans(13,'rename_MAX_NVAR(1)-->2',13).
spec_trans(13,'rename_MAX_NVAR(2)-->2',13).
spec_trans(13,'rename_PRE_INC_NVAR-->FALSE',13).
spec_trans(13,'rename_PRE_DEC_NVAR-->TRUE',13).
spec_trans(13,rename_DEC_NVAR,12).
spec_trans(13,'rename_PRE_ADD_NVAR(0)-->TRUE',13).
spec_trans(13,'rename_PRE_ADD_NVAR(1)-->FALSE',13).
spec_trans(13,'rename_PRE_ADD_NVAR(2)-->FALSE',13).
spec_trans(13,'rename_ADD_NVAR(0)',13).
spec_trans(13,'rename_PRE_MUL_NVAR(0)-->TRUE',13).
spec_trans(13,'rename_PRE_MUL_NVAR(1)-->TRUE',13).
spec_trans(13,'rename_PRE_MUL_NVAR(2)-->FALSE',13).
spec_trans(13,'rename_MUL_NVAR(0)',10).
spec_trans(13,'rename_MUL_NVAR(1)',13).
spec_trans(13,'rename_PRE_SUB_NVAR(0)-->TRUE',13).
spec_trans(13,'rename_PRE_SUB_NVAR(1)-->TRUE',13).
spec_trans(13,'rename_PRE_SUB_NVAR(2)-->TRUE',13).
spec_trans(13,'rename_SUB_NVAR(0)',13).
spec_trans(13,'rename_SUB_NVAR(1)',12).
spec_trans(13,'rename_SUB_NVAR(2)',10).
spec_trans(13,'rename_PRE_DIV_NVAR(0)-->FALSE',13).
spec_trans(13,'rename_PRE_DIV_NVAR(1)-->TRUE',13).
spec_trans(13,'rename_PRE_DIV_NVAR(2)-->TRUE',13).
spec_trans(13,'rename_DIV_NVAR(1)',13).
spec_trans(13,'rename_DIV_NVAR(2)',12).
spec_trans(13,'rename_PRE_MOD_NVAR(0)-->FALSE',13).
spec_trans(13,'rename_PRE_MOD_NVAR(1)-->TRUE',13).
spec_trans(13,'rename_PRE_MOD_NVAR(2)-->TRUE',13).
spec_trans(13,'rename_MOD_NVAR(1)',10).
spec_trans(13,'rename_MOD_NVAR(2)',10).
spec_trans(13,'rename_EQL_NVAR(0)-->FALSE',13).
spec_trans(13,'rename_EQL_NVAR(1)-->FALSE',13).
spec_trans(13,'rename_EQL_NVAR(2)-->TRUE',13).
spec_trans(13,'rename_NEQ_NVAR(0)-->TRUE',13).
spec_trans(13,'rename_NEQ_NVAR(1)-->TRUE',13).
spec_trans(13,'rename_NEQ_NVAR(2)-->FALSE',13).
spec_trans(13,'rename_GTR_NVAR(0)-->TRUE',13).
spec_trans(13,'rename_GTR_NVAR(1)-->TRUE',13).
spec_trans(13,'rename_GTR_NVAR(2)-->FALSE',13).
spec_trans(13,'rename_GEQ_NVAR(0)-->TRUE',13).
spec_trans(13,'rename_GEQ_NVAR(1)-->TRUE',13).
spec_trans(13,'rename_GEQ_NVAR(2)-->TRUE',13).
spec_trans(13,'rename_SMR_NVAR(0)-->FALSE',13).
spec_trans(13,'rename_SMR_NVAR(1)-->FALSE',13).
spec_trans(13,'rename_SMR_NVAR(2)-->FALSE',13).
spec_trans(13,'rename_LEQ_NVAR(0)-->FALSE',13).
spec_trans(13,'rename_LEQ_NVAR(1)-->FALSE',13).
spec_trans(13,'rename_LEQ_NVAR(2)-->TRUE',13).
spec_trans(13,rename_SAV_NVAR,13).
spec_trans(13,rename_RST_NVAR,10).
spec_trans(13,rename_RST_NVAR,12).
spec_trans(13,rename_RST_NVAR,13).
spec_trans(13,rename_SAVN_NVAR,13).
spec_trans(13,rename_RSTN_NVAR,10).
spec_trans(13,rename_RSTN_NVAR,12).
spec_trans(13,rename_RSTN_NVAR,13).
spec_max_reached_for_node(root).
spec_not_all_transitions_added(_) :-
        fail.
spec_completely_explored :-
        fail.
