spec_trans(root,'$initialise_machine',0).
spec_trans(0,resetread,0).
spec_trans(0,incread,1).
spec_trans(0,'enter(ELEM1)',2).
spec_trans(0,'enter(ELEM2)',3).
spec_trans(1,resetread,0).
spec_trans(1,incread,4).
spec_trans(1,'enter(ELEM1)',5).
spec_trans(1,'enter(ELEM2)',6).
spec_trans(3,resetread,3).
spec_trans(3,incread,6).
spec_trans(3,'enter(ELEM1)',7).
spec_trans(3,'enter(ELEM2)',8).
spec_trans(2,resetread,2).
spec_trans(2,incread,5).
spec_trans(2,'enter(ELEM1)',9).
spec_trans(2,'enter(ELEM2)',10).
spec_trans(4,resetread,0).
spec_trans(4,incread,11).
spec_trans(4,'enter(ELEM1)',12).
spec_trans(4,'enter(ELEM2)',13).
spec_trans(5,'lookup-->ELEM1',5).
spec_trans(5,resetread,2).
spec_trans(5,incread,12).
spec_trans(5,'enter(ELEM1)',14).
spec_trans(5,'enter(ELEM2)',15).
spec_trans(6,'lookup-->ELEM2',6).
spec_trans(6,resetread,3).
spec_trans(6,incread,13).
spec_trans(6,'enter(ELEM1)',16).
spec_trans(6,'enter(ELEM2)',17).
spec_trans(7,resetread,7).
spec_trans(7,incread,16).
spec_trans(7,'enter(ELEM1)',18).
spec_trans(7,'enter(ELEM2)',19).
spec_trans(14,'lookup-->ELEM1',14).
spec_trans(14,resetread,9).
spec_trans(14,incread,20).
spec_trans(14,'enter(ELEM1)',21).
spec_trans(14,'enter(ELEM2)',22).
spec_trans(8,resetread,8).
spec_trans(8,incread,17).
spec_trans(8,'enter(ELEM1)',23).
spec_trans(8,'enter(ELEM2)',24).
spec_trans(9,resetread,9).
spec_trans(9,incread,14).
spec_trans(9,'enter(ELEM1)',25).
spec_trans(9,'enter(ELEM2)',26).
spec_trans(22,'lookup-->ELEM1',22).
spec_trans(22,resetread,26).
spec_trans(22,incread,27).
spec_trans(22,'enter(ELEM1)',28).
spec_trans(22,'enter(ELEM2)',29).
spec_trans(29,'lookup-->ELEM1',29).
spec_trans(29,resetread,30).
spec_trans(29,incread,31).
spec_trans(29,'enter(ELEM1)',32).
spec_trans(29,'enter(ELEM2)',33).
spec_trans(10,resetread,10).
spec_trans(10,incread,15).
spec_trans(10,'enter(ELEM1)',34).
spec_trans(10,'enter(ELEM2)',35).
spec_trans(11,resetread,0).
spec_trans(11,incread,36).
spec_trans(11,'enter(ELEM1)',37).
spec_trans(11,'enter(ELEM2)',38).
spec_trans(36,resetread,0).
spec_trans(36,incread,39).
spec_trans(36,'enter(ELEM1)',40).
spec_trans(36,'enter(ELEM2)',41).
spec_not_all_transitions_added(41).
spec_not_all_transitions_added(40).
spec_not_all_transitions_added(39).
spec_not_all_transitions_added(35).
spec_not_all_transitions_added(33).
spec_not_all_transitions_added(32).
spec_not_all_transitions_added(31).
spec_not_all_transitions_added(30).
spec_not_all_transitions_added(28).
spec_not_all_transitions_added(27).
spec_not_all_transitions_added(21).
spec_not_all_transitions_added(20).
spec_not_all_transitions_added(12).
spec_not_all_transitions_added(13).
spec_not_all_transitions_added(15).
spec_not_all_transitions_added(16).
spec_not_all_transitions_added(17).
spec_not_all_transitions_added(18).
spec_not_all_transitions_added(19).
spec_not_all_transitions_added(23).
spec_not_all_transitions_added(24).
spec_not_all_transitions_added(25).
spec_not_all_transitions_added(26).
spec_not_all_transitions_added(34).
spec_not_all_transitions_added(37).
spec_not_all_transitions_added(38).
spec_max_reached_for_node(_) :-
        fail.
spec_completely_explored :-
        fail.
