spec_trans(root,'$initialise_machine',4).
spec_trans(root,'$initialise_machine',11).
spec_trans(root,'$initialise_machine',3).
spec_trans(2,'$initialise_machine',3).
spec_trans(0,'$initialise_machine',4).
spec_trans(3,'join_queue(NAME1)',5).
spec_trans(3,'join_queue(NAME2)',6).
spec_trans(3,semi_reset,3).
spec_trans(3,'query_membership(NAME1)-->no',3).
spec_trans(3,'query_membership(NAME2)-->no',3).
spec_trans(6,'join(NAME2)',7).
spec_trans(6,'join_queue(NAME1)',8).
spec_trans(6,semi_reset,3).
spec_trans(6,'query_membership(NAME1)-->no',6).
spec_trans(6,'query_membership(NAME2)-->no',6).
spec_trans(8,'join(NAME1)',9).
spec_trans(8,'join(NAME2)',10).
spec_trans(8,semi_reset,3).
spec_trans(8,'query_membership(NAME1)-->no',8).
spec_trans(8,'query_membership(NAME2)-->no',8).
spec_trans(1,'$initialise_machine',11).
spec_trans(10,'remove(NAME2)',5).
spec_trans(10,semi_reset,6).
spec_trans(10,'query_membership(NAME1)-->no',10).
spec_trans(10,'query_membership(NAME2)-->yes',10).
spec_trans(4,'join_queue(NAME1)',12).
spec_trans(4,'join_queue(NAME2)',13).
spec_trans(4,semi_reset,4).
spec_trans(4,'query_membership(NAME1)-->no',4).
spec_trans(4,'query_membership(NAME2)-->no',4).
spec_trans(9,'remove(NAME1)',6).
spec_trans(9,semi_reset,5).
spec_trans(9,'query_membership(NAME1)-->yes',9).
spec_trans(9,'query_membership(NAME2)-->no',9).
spec_trans(5,'join(NAME1)',14).
spec_trans(5,'join_queue(NAME2)',8).
spec_trans(5,semi_reset,3).
spec_trans(5,'query_membership(NAME1)-->no',5).
spec_trans(5,'query_membership(NAME2)-->no',5).
spec_trans(14,'join_queue(NAME2)',9).
spec_trans(14,'remove(NAME1)',3).
spec_trans(14,semi_reset,5).
spec_trans(14,'query_membership(NAME1)-->yes',14).
spec_trans(14,'query_membership(NAME2)-->no',14).
spec_trans(7,'join_queue(NAME1)',10).
spec_trans(7,'remove(NAME2)',3).
spec_trans(7,semi_reset,6).
spec_trans(7,'query_membership(NAME1)-->no',7).
spec_trans(7,'query_membership(NAME2)-->yes',7).
spec_trans(11,'join_queue(NAME1)',15).
spec_trans(11,'join_queue(NAME2)',16).
spec_trans(11,semi_reset,11).
spec_trans(11,'query_membership(NAME1)-->no',11).
spec_trans(11,'query_membership(NAME2)-->no',11).
spec_trans(16,'join(NAME2)',17).
spec_trans(16,'join_queue(NAME1)',18).
spec_trans(16,semi_reset,11).
spec_trans(16,'query_membership(NAME1)-->no',16).
spec_trans(16,'query_membership(NAME2)-->no',16).
spec_trans(12,'join(NAME1)',19).
spec_trans(12,semi_reset,4).
spec_trans(12,'query_membership(NAME1)-->no',12).
spec_trans(12,'query_membership(NAME2)-->no',12).
spec_trans(18,'join(NAME1)',20).
spec_trans(18,'join(NAME2)',21).
spec_trans(18,semi_reset,11).
spec_trans(18,'query_membership(NAME1)-->no',18).
spec_trans(18,'query_membership(NAME2)-->no',18).
spec_trans(21,'remove(NAME2)',15).
spec_trans(21,semi_reset,16).
spec_trans(21,'query_membership(NAME1)-->no',21).
spec_trans(21,'query_membership(NAME2)-->yes',21).
spec_trans(13,'join(NAME2)',22).
spec_trans(13,semi_reset,4).
spec_trans(13,'query_membership(NAME1)-->no',13).
spec_trans(13,'query_membership(NAME2)-->no',13).
spec_trans(15,'join(NAME1)',23).
spec_trans(15,'join_queue(NAME2)',18).
spec_trans(15,semi_reset,11).
spec_trans(15,'query_membership(NAME1)-->no',15).
spec_trans(15,'query_membership(NAME2)-->no',15).
spec_trans(20,'remove(NAME1)',16).
spec_trans(20,semi_reset,15).
spec_trans(20,'query_membership(NAME1)-->yes',20).
spec_trans(20,'query_membership(NAME2)-->no',20).
spec_trans(17,'join_queue(NAME1)',21).
spec_trans(17,'remove(NAME2)',11).
spec_trans(17,semi_reset,16).
spec_trans(17,'query_membership(NAME1)-->no',17).
spec_trans(17,'query_membership(NAME2)-->yes',17).
spec_trans(19,'join_queue(NAME2)',24).
spec_trans(19,'remove(NAME1)',4).
spec_trans(19,semi_reset,12).
spec_trans(19,'query_membership(NAME1)-->yes',19).
spec_trans(19,'query_membership(NAME2)-->no',19).
spec_trans(24,'remove(NAME1)',13).
spec_trans(24,semi_reset,12).
spec_trans(24,'query_membership(NAME1)-->yes',24).
spec_trans(24,'query_membership(NAME2)-->no',24).
spec_trans(22,'join_queue(NAME1)',25).
spec_trans(22,'remove(NAME2)',4).
spec_trans(22,semi_reset,13).
spec_trans(22,'query_membership(NAME1)-->no',22).
spec_trans(22,'query_membership(NAME2)-->yes',22).
spec_trans(23,'join_queue(NAME2)',20).
spec_trans(23,'remove(NAME1)',11).
spec_trans(23,semi_reset,15).
spec_trans(23,'query_membership(NAME1)-->yes',23).
spec_trans(23,'query_membership(NAME2)-->no',23).
spec_trans(25,'remove(NAME2)',12).
spec_trans(25,semi_reset,13).
spec_trans(25,'query_membership(NAME1)-->no',25).
spec_trans(25,'query_membership(NAME2)-->yes',25).
spec_not_all_transitions_added(_) :-
        fail.
spec_max_reached_for_node(_) :-
        fail.
spec_completely_explored.
