spec_trans(root,'$initialise_machine',0).
spec_trans(0,'born(PERSON1,boy)',1).
spec_trans(0,'born(PERSON1,girl)',2).
spec_trans(0,'born(PERSON2,boy)',3).
spec_trans(0,'born(PERSON2,girl)',4).
spec_trans(1,'born(PERSON2,boy)',5).
spec_trans(1,'born(PERSON2,girl)',6).
spec_trans(1,'die(PERSON1)',0).
spec_trans(4,'born(PERSON1,boy)',6).
spec_trans(4,'born(PERSON1,girl)',7).
spec_trans(4,'die(PERSON2)',0).
spec_trans(7,'die(PERSON1)',4).
spec_trans(7,'die(PERSON2)',2).
spec_trans(2,'born(PERSON2,boy)',8).
spec_trans(2,'born(PERSON2,girl)',7).
spec_trans(2,'die(PERSON1)',0).
spec_trans(3,'born(PERSON1,boy)',5).
spec_trans(3,'born(PERSON1,girl)',8).
spec_trans(3,'die(PERSON2)',0).
spec_trans(5,'die(PERSON1)',3).
spec_trans(5,'die(PERSON2)',1).
spec_trans(6,'die(PERSON1)',4).
spec_trans(6,'die(PERSON2)',1).
spec_trans(8,'die(PERSON1)',3).
spec_trans(8,'die(PERSON2)',2).
spec_not_all_transitions_added(_) :-
        fail.
spec_max_reached_for_node(_) :-
        fail.
spec_completely_explored.
